[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[profile.dependencies]
OpenZeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v4.5.0" }
chainlink = { git = "https://github.com/smartcontractkit/chainlink", tag = "v0.10.12" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
